config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :articles
  before_save { self.email = email.downcase }
  validates :username, presence: true, length: { minimum: 3, maximum: 25 }, uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:danger] = 'You must be logged in'
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_article, only: %i[edit update show destroy]
  before_action :require_user, except: %i[index show]
  before_action :require_same_user, only: %i[edit update destroy]
  def index
    @pagy, @articles = pagy(Article.all, items: 3)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = 'Article was successfully created'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = 'Article was successfully updated'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show # rubocop:disable Style/EmptyMethod
  end

  def edit # rubocop:disable Style/EmptyMethod
  end

  def destroy
    @article.destroy
    flash[:danger] = 'Article was successfully deleted'
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user
      flash[:danger] = 'You can only edit or delete your own article'
      redirect_to root_path
    end
  end
end

app/controllers/page_controller.rb
# frozen_string_literal: true

class PageController < ApplicationController
  def home; end

  def about; end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about; end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'You have successfully logged in'
      redirect_to user_path(user)
    else
      flash.now[:danger] = 'There was somthing wrong with your login information'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have successfully logged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update show]
  before_action :require_same_user, only: %i[edit update]

  def index
    @pagy, @users = pagy(User.all, items: 4)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Alpha Blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = 'Your account was updated suucessfully'
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @pagy, @users_articles = pagy(@user.articles.all, items: 4)
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:danger] = 'You can only edit your own account'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'rounded-circle')
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article|%>
  <div class="row">
    <div class="col-8 offset-2">
      <div class="card">
        <div class="article-title card-header">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body card-body">
          <%= truncate(article.description, length: 100) %>
        <div class='article-meta-details'>
           <small>Created by: <%= article.user.username if article.user %>,
          <%= time_ago_in_words(article.created_at) %> ago,
          last updated: <%= time_ago_in_words(article.updated_at) %> ago
          </small>
        </div>
        </div>
        <% if logged_in? && current_user == article.user %>
          <div class="article-actions card-footer">
            <%= link_to 'Edit this article', edit_article_path(article), class: 'btn btn-primary custom-btn' %>
            <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete the article?"},class: 'btn btn-danger' %>
          </div>
        <%end%>
      </div>
    </div>
  </div>
<%end%>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class='row'>
  <div class='col-12 col-auto'>
    <%= form_for @article do |f| %>
      <div class='form-group row'>
        <%= f.label :title, class: 'col-sm-2 col-form-label'  %>
        <div class='col-sm-10'>
          <%= f.text_field :title, class: 'form-control', placeholder: 'Title of article', autofocus: true %>
        </div>
      </div>
      <div class='form-group row'>
        <%= f.label :description, class: 'col-sm-2 col-form-label'  %>
        <div class='col-sm-10'>
          <%= f.text_area :description,rows: 10, class: 'form-control', placeholder: 'Body of article', autofocus: true %>
        </div>
      </div>
      <div class="form-group row">
        <div class="offset-sm-2 col-sm-8">
          <%= f.submit class: 'btn btn-primary btn-lg custom-btn' %>
        </div>
      </div>
    <% end %>
    <div class='col-4 offset-4'>
      [ <%= link_to 'Cancel request and return to articles listing', articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class='text-center mt-4'>Edit existing articles</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center"> Listing all articles </h1>
<div class='text-center'>
  <%== pagy_bootstrap_nav(@pagy).html_safe %>
<div>
<%= render 'articles/article', obj: @articles %>
<div class='text-center'>
  <%== pagy_bootstrap_nav(@pagy).html_safe %>
<div>

app/views/articles/new.html.erb
<h1 class='text-center mt-4'> Create an Article </h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center"> Title: <%= @article.title %> </h2>
<div class="card card-body bg-light col-8 offset-2">
<%if @article.user %>
<ul class='listing'>
    <div class='row text-center'>
      <div class='col-md-4 offset-4'>
      <li>Created by: </li>
        <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %>
        <li class='article-title'>
          <%= link_to  @article.user.username, user_path(@article.user) %>
        </li>
        <li><small><%= pluralize(@article.user.articles.count, 'article') if @article.user.articles %></small></li>
      </div>
    </div>
  </ul>
  <%end%>
  <h4 class="text-center description"><strong>Description:</strong></h4> 
  <hr>
    <%= simple_format(@article.description) %>
    <div class="article-actions">
    <% if logged_in? && current_user == @article.user %>
      <%= link_to 'Edit this article', edit_article_path(@article), class: 'btn btn-primary custom-btn' %>
      <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete the article?"},class: 'btn btn-danger' %>
    <%end%>
      <%= link_to 'View all articles', articles_path, class: 'btn btn-success' %>
    </div>
  </div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; <a href="#"> Alpha Blog</a>
      by <a href="#">Damilola Ale</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to 'About', about_path %> 
        </ul>
      </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-10 offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %> '>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-5">
  <%= link_to 'Alpha Blog', root_path, class: 'navbar-brand', id: 'logo' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if logged_in? %>
      <li class="nav-link">
        <%= link_to 'Articles', articles_path,class: 'text-white' %>
      </li>
      <li class="nav-link">
        <%= link_to 'New Article', new_article_path(current_user), class:'text-white' %>
      </li>
      <li class="nav-link">
        <%= link_to 'Users',users_path, class:'text-white' %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Edit profile', edit_user_path(current_user), class: 'dropdown-item' %>
          <%= link_to 'View profile', user_path(current_user), class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    </ul>
    <li class="nav-link">
      <%= link_to 'Log out', logout_path, method: :delete,class: 'text-white' %>
    </li>
    <%else%>
      <li class="nav-link">
        <%= link_to 'Log in', login_path,class: 'text-white' %>
      </li>
      <li class="nav-link">
        <%= link_to 'Sign Up', signup_path,class: 'text-white' %>
      </li>
    <%end%>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> This is the about page <h1>

<%= link_to 'Home',  root_path %>

app/views/pages/home.html.erb
<div class="jumbotron mt-3">
  <div class="text-div">
    <h1>ALPHA BLOG</h1>
    <%= link_to 'Sign up now', signup_path, class: "btn btn-lg nav-button text-white" %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row mb-5">
    <div class="offset-2 col-8">
      <div class="alert alert-danger alert-dismissible" role="alert">
        <div>
          <h2 class="alert-heading">
            <%= pluralize(obj.errors.count, 'error') %>
            Prohibited this article from being saved
          </h2>
          <div>
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class='row'>
  <div class='col-12 col-auto'>
    <%= form_for @user do |f| %>
      <div class='form-group row'>
        <%= f.label :username, class: 'col-sm-2 col-form-label'  %>
        <div class='col-sm-10'>
          <%= f.text_field :username, class: 'form-control', placeholder: 'Enter username', autofocus: true %>
        </div>
      </div>
      <div class='form-group row'>
        <%= f.label :password, class: 'col-sm-2 col-form-label'  %>
        <div class='col-sm-10'>
          <%= f.password_field :password, class: 'form-control', placeholder: 'Enter password', autofocus: true %>
        </div>
      </div>
      <div class='form-group row'>
        <%= f.label :email, class: 'col-sm-2 col-form-label'  %>
        <div class='col-sm-10'>
          <%= f.email_field :email, class: 'form-control', placeholder: 'Enter email', autofocus: true %>
        </div>
      </div>
      <div class="form-group row">
        <div class="offset-sm-2 col-sm-8">
          <%= f.submit(@user.new_record? ? 'Sign up' : 'Update account', class: 'btn btn-primary btn-lg custom-btn') %>
        </div>
      </div>
    <% end %>
    <div class='col-4 offset-4'>
      [ <%= link_to 'Cancel request and return to articles listing', articles_path %> ]
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class='text-center'>Edit your account</h1>
<%= render 'users/form' %>

app/views/users/index.html.erb
<h1 class='text-center'>All Alpha Bloggers</h1>
<div class='text-center'>
 <%== pagy_bootstrap_nav(@pagy).html_safe %>
  <% @users.each do |user| %>
  <ul class='listing'>
    <div class='row'>
      <div class='card col-md-4 offset-4'>
        <li><%= link_to gravatar_for(user), user_path(user) %>
        <li class='article-title'>
          <%= link_to  user.username, user_path(user) %>
        </li>
        <li><small><%= pluralize(user.articles.count, 'article') if user.articles %></small></li>
      </div>
    </div>
  </ul>
<%end%>
</div>
<div class='text-center'>
  <%== pagy_bootstrap_nav(@pagy).html_safe %>
<div>

app/views/users/new.html.erb
<h1 class='text-center'>Sign up for Alpha Blog<h1>
<%= render 'users/form' %>

app/views/users/show.html.erb
<h1 class='text-center'>Welcome to your page <%= @user.username %></h1>
<div class='row'>
  <div class='col-md-4 offset-4  mx-auto d-block text-center'>
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<h4 class=text-center><%= @user.username %>'articles</h4>
<div class='text-center'>
   <%== pagy_bootstrap_nav(@pagy).html_safe %>
</div>
<%= render'articles/article', obj: @user.articles %>